FROM node:16.13.1

WORKDIR /app

RUN apt-get update && apt-get install -y curl

ARG NPM_TOKEN
COPY config/docker/.npmrc ./
COPY package*.json ./

RUN npm i

COPY . .

CMD ["/app/node_modules/.bin/migrate-mongo", "up"]
