#!/usr/bin/env bash

error() {
  echo "🚨 Error: $1"
  exit 1
}

daemon_mode() {
  local DAEMON_MODE=${ZZM_SERVICES_DAEMON_MODE:-""}
  if [ "$DAEMON_MODE" ]; then
    echo "-d"
    exit 0
  fi
  echo ""
}

assert_not_uncommitted_changes() {
  if [[ $(git status --porcelain) ]]; then
    git status
    error "There are uncommitted changes in the working tree."
  fi
}

assert_main_branch() {
  local -r BRANCH=$(git rev-parse --abbrev-ref HEAD)
  if [[ ${BRANCH} == 'main' ]]; then
    echo "Main branch"
  else
    error "Invalid branch name ${BRANCH}"
  fi
}

compare_version() {
  IFS='.' read -ra ver1 <<<"$1"
  IFS='.' read -ra ver2 <<<"$2"

  [[ ${#ver1[@]} -gt ${#ver2[@]} ]] && till=${#ver1[@]} || till=${#ver2[@]}

  for ((i = 0; i < ${till}; i++)); do

    local num1
    local num2

    [[ -z ${ver1[i]} ]] && num1=0 || num1=${ver1[i]}
    [[ -z ${ver2[i]} ]] && num2=0 || num2=${ver2[i]}

    if [[ $num1 -gt $num2 ]]; then
      echo ">"
      return 0
    elif
      [[ $num1 -lt $num2 ]]
    then
      echo "<"
      return 0
    fi
  done
  echo "="
  return 0
}
